dataset:
  train_path: hebrew_diacritized/train
  val_path: hebrew_diacritized/validation
  test_path: hebrew_diacritized/test_modern
  max_len: 100
  min_len: 10

model_name: menakbert_y1
hyper_params:
  lr: 0.00001
  dropout: 0.1
  batch_size: 32
  gradient accumilation: 1
  max epochs: 5
  train_batchsize: 32
  val_batchsize: 32

